import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export const useThemesStore = defineStore('themes', () => {
  // 主题分类
  const categories = ref([
    { id: 'all', name: '全部' },
    { id: 'study', name: '学习' },
    { id: 'sports', name: '运动' },
    { id: 'aesthetic', name: '美育' },
    { id: 'psychology', name: '心理' },
    { id: 'culture', name: '文化' },
    { id: 'skills', name: '技能' },
    { id: 'travel', name: '旅行' },
    { id: 'handicraft', name: '手工' },
    { id: 'social', name: '社交' },
    { id: 'life', name: '生活' },
    { id: 'health', name: '健康' },
    { id: 'language', name: '语言' },
  ]);

  // 主题列表 - 每个分类至少12个
  const themes = ref([
    // 学习类 (12个)
    {
      id: 1,
      icon: '📖',
      name: '阅读周',
      description: '放下手机，沉浸在文字的世界里',
      category: 'study',
      tags: ['学习', '阅读'],
      participants: 512,
      ideas: ['读完一本书', '写读书笔记', '分享读书心得'],
    },
    {
      id: 2,
      icon: '📚',
      name: '历史周',
      description: '穿越时空，了解人类文明的足迹',
      category: 'study',
      tags: ['学习', '知识'],
      participants: 156,
      ideas: ['读一本历史书', '看一部历史纪录片', '了解一个历史时期'],
    },
    {
      id: 3,
      icon: '🔬',
      name: '科学周',
      description: '探索科学的奥秘，满足好奇心',
      category: 'study',
      tags: ['学习', '知识'],
      participants: 189,
      ideas: ['做一个科学小实验', '看一部科普纪录片', '了解一个科学原理'],
    },
    {
      id: 4,
      icon: '🌍',
      name: '地理周',
      description: '了解世界，拓宽视野',
      category: 'study',
      tags: ['学习', '知识'],
      participants: 134,
      ideas: ['了解一个国家', '看一部地理纪录片', '学习地理知识'],
    },
    {
      id: 5,
      icon: '🧮',
      name: '数学周',
      description: '探索数学之美，训练逻辑思维',
      category: 'study',
      tags: ['学习', '思维'],
      participants: 98,
      ideas: ['解决一道难题', '了解数学史', '学习速算技巧'],
    },
    {
      id: 6,
      icon: '📊',
      name: '数据周',
      description: '用数据看世界，发现隐藏的规律',
      category: 'study',
      tags: ['学习', '技能'],
      participants: 167,
      ideas: ['学习Excel高级功能', '做一个数据分析', '了解统计学基础'],
    },
    {
      id: 7,
      icon: '🤔',
      name: '哲学周',
      description: '思考人生意义，探索智慧之道',
      category: 'study',
      tags: ['学习', '思维'],
      participants: 123,
      ideas: ['读一本哲学书', '思考一个哲学问题', '了解一位哲学家'],
    },
    {
      id: 8,
      icon: '🔭',
      name: '天文周',
      description: '仰望星空，探索宇宙的奥秘',
      category: 'study',
      tags: ['学习', '自然'],
      participants: 145,
      ideas: ['认识星座', '观测月亮', '了解太阳系'],
    },
    {
      id: 9,
      icon: '🦕',
      name: '古生物周',
      description: '穿越远古，了解生命演化史',
      category: 'study',
      tags: ['学习', '自然'],
      participants: 89,
      ideas: ['了解恐龙种类', '参观自然博物馆', '看古生物纪录片'],
    },
    {
      id: 10,
      icon: '🏛️',
      name: '建筑周',
      description: '欣赏建筑之美，了解设计原理',
      category: 'study',
      tags: ['学习', '艺术'],
      participants: 112,
      ideas: ['了解一种建筑风格', '参观特色建筑', '学习建筑史'],
    },
    {
      id: 11,
      icon: '📋',
      name: '法律周',
      description: '了解法律知识，维护自身权益',
      category: 'study',
      tags: ['学习', '实用'],
      participants: 134,
      ideas: ['了解基础法律知识', '学习合同法', '了解劳动法'],
    },
    {
      id: 12,
      icon: '💰',
      name: '理财周',
      description: '学习理财知识，规划财务自由',
      category: 'study',
      tags: ['学习', '实用'],
      participants: 289,
      ideas: ['了解理财产品', '学习投资知识', '制定储蓄计划'],
    },

    // 运动类 (12个)
    {
      id: 13,
      icon: '🏃',
      name: '跑步周',
      description: '用脚步丈量城市，感受奔跑的快乐',
      category: 'sports',
      tags: ['运动', '健康'],
      participants: 398,
      ideas: ['每天跑步3公里', '尝试间歇跑', '参加一次跑步活动'],
    },
    {
      id: 14,
      icon: '🏊',
      name: '游泳周',
      description: '在水中感受自由，锻炼身体',
      category: 'sports',
      tags: ['运动', '健康'],
      participants: 234,
      ideas: ['每天游泳30分钟', '学习一种泳姿', '提高游泳速度'],
    },
    {
      id: 15,
      icon: '🚴',
      name: '骑行周',
      description: '用两个轮子探索城市，感受风的自由',
      category: 'sports',
      tags: ['运动', '健康'],
      participants: 267,
      ideas: ['每天骑行5公里', '探索一条新路线', '记录骑行轨迹'],
    },
    {
      id: 16,
      icon: '🧘',
      name: '瑜伽周',
      description: '在呼吸与伸展中，找到身心的平衡',
      category: 'sports',
      tags: ['运动', '健康'],
      participants: 345,
      ideas: ['每天练习瑜伽20分钟', '学习基础体式', '尝试冥想瑜伽'],
    },
    {
      id: 17,
      icon: '🥊',
      name: '拳击周',
      description: '释放力量，挑战自我极限',
      category: 'sports',
      tags: ['运动', '力量'],
      participants: 156,
      ideas: ['学习基本拳法', '练习组合拳', '进行体能训练'],
    },
    {
      id: 18,
      icon: '⛹️',
      name: '篮球周',
      description: '在球场上挥洒汗水，感受团队配合',
      category: 'sports',
      tags: ['运动', '团队'],
      participants: 289,
      ideas: ['练习投篮', '学习运球技巧', '打一场友谊赛'],
    },
    {
      id: 19,
      icon: '⚽',
      name: '足球周',
      description: '世界第一运动，感受激情与速度',
      category: 'sports',
      tags: ['运动', '团队'],
      participants: 312,
      ideas: ['练习带球', '学习传球技巧', '看一场经典比赛'],
    },
    {
      id: 20,
      icon: '🎾',
      name: '网球周',
      description: '优雅与力量的结合，享受击球快感',
      category: 'sports',
      tags: ['运动', '技巧'],
      participants: 178,
      ideas: ['练习发球', '学习正手击球', '找搭档对打'],
    },
    {
      id: 21,
      icon: '🏸',
      name: '羽毛球周',
      description: '轻盈灵动，享受快速反应的乐趣',
      category: 'sports',
      tags: ['运动', '技巧'],
      participants: 234,
      ideas: ['练习挥拍', '学习步伐移动', '进行双打练习'],
    },
    {
      id: 22,
      icon: '🧗',
      name: '攀岩周',
      description: '挑战自我，突破极限',
      category: 'sports',
      tags: ['运动', '挑战'],
      participants: 145,
      ideas: ['体验一次室内攀岩', '学习基本技巧', '完成一条线路'],
    },
    {
      id: 23,
      icon: '🤸',
      name: '体操周',
      description: '训练身体协调性，塑造优美体态',
      category: 'sports',
      tags: ['运动', '柔韧'],
      participants: 98,
      ideas: ['练习基本功', '学习翻滚动作', '进行拉伸训练'],
    },
    {
      id: 24,
      icon: '🏓',
      name: '乒乓球周',
      description: '国球魅力，锻炼反应与技巧',
      category: 'sports',
      tags: ['运动', '技巧'],
      participants: 267,
      ideas: ['练习发球', '学习旋球', '找对手切磋'],
    },

    // 美育类 (12个)
    {
      id: 25,
      icon: '🎼',
      name: '音乐剧周',
      description: '走进剧场，感受音乐与戏剧的碰撞',
      category: 'aesthetic',
      tags: ['美育', '音乐'],
      participants: 328,
      ideas: ['观看一场现场音乐剧', '学唱一首经典音乐剧选段', '了解音乐剧的发展历史'],
    },
    {
      id: 26,
      icon: '🎨',
      name: '绘画周',
      description: '用画笔记录生活，表达内心世界',
      category: 'aesthetic',
      tags: ['美育', '创作'],
      participants: 143,
      ideas: ['每天画一幅画', '尝试不同画材', '学习构图技巧'],
    },
    {
      id: 27,
      icon: '🎧',
      name: '音乐周',
      description: '聆听不同风格的音乐，感受旋律的力量',
      category: 'aesthetic',
      tags: ['美育', '音乐'],
      participants: 287,
      ideas: ['每天听一张专辑', '学习一种乐器', '了解音乐流派'],
    },
    {
      id: 28,
      icon: '🎸',
      name: '吉他周',
      description: '拨动琴弦，用音乐表达自己',
      category: 'aesthetic',
      tags: ['美育', '音乐'],
      participants: 203,
      ideas: ['学会基础和弦', '弹唱一首歌', '练习指法'],
    },
    {
      id: 29,
      icon: '🎬',
      name: '观影周',
      description: '每天一部电影，体验不同的人生',
      category: 'aesthetic',
      tags: ['美育', '电影'],
      participants: 267,
      ideas: ['每天看一部电影', '写影评', '了解电影制作'],
    },
    {
      id: 30,
      icon: '📸',
      name: '摄影周',
      description: '用镜头捕捉生活中的美好瞬间',
      category: 'aesthetic',
      tags: ['美育', '记录'],
      participants: 234,
      ideas: ['每天拍一张主题照片', '学习构图技巧', '制作摄影集'],
    },
    {
      id: 31,
      icon: '💃',
      name: '舞蹈周',
      description: '用身体感受节奏，释放内心激情',
      category: 'aesthetic',
      tags: ['美育', '表演'],
      participants: 176,
      ideas: ['学习一种舞蹈风格', '每天练习基本功', '录制一段舞蹈视频'],
    },
    {
      id: 32,
      icon: '🎪',
      name: '戏剧周',
      description: '走进戏剧世界，体验不同的人生故事',
      category: 'aesthetic',
      tags: ['美育', '表演'],
      participants: 112,
      ideas: ['观看一场话剧', '尝试即兴表演', '了解戏剧流派'],
    },
    {
      id: 33,
      icon: '🎹',
      name: '钢琴周',
      description: '黑白键上的艺术，培养音乐素养',
      category: 'aesthetic',
      tags: ['美育', '音乐'],
      participants: 198,
      ideas: ['练习一首曲子', '学习乐理知识', '了解钢琴家故事'],
    },
    {
      id: 34,
      icon: '🎵',
      name: '歌唱周',
      description: '用歌声表达情感，享受音乐魅力',
      category: 'aesthetic',
      tags: ['美育', '音乐'],
      participants: 245,
      ideas: ['每天练声', '学习一首新歌', '了解发声技巧'],
    },
    {
      id: 35,
      icon: '🖌️',
      name: '水彩周',
      description: '用水彩描绘心中的色彩世界',
      category: 'aesthetic',
      tags: ['美育', '绘画'],
      participants: 167,
      ideas: ['学习水彩基础技法', '完成一幅风景画', '尝试湿画法'],
    },
    {
      id: 38,
      icon: '🎭',
      name: '皮影周',
      description: '探索传统皮影艺术，感受非遗魅力',
      category: 'aesthetic',
      tags: ['美育', '传统'],
      participants: 67,
      ideas: ['了解皮影历史', '制作简易皮影', '表演皮影戏'],
    },

    // 心理类 (12个)
    {
      id: 37,
      icon: '🧠',
      name: '冥想周',
      description: '静下心来，与自己对话',
      category: 'psychology',
      tags: ['心理', '健康'],
      participants: 356,
      ideas: ['每天冥想10分钟', '尝试不同冥想方式', '记录内心感受'],
    },
    {
      id: 38,
      icon: '🧩',
      name: '心理学周',
      description: '了解心理学，更好地认识自己和他人',
      category: 'psychology',
      tags: ['心理', '成长'],
      participants: 267,
      ideas: ['读一本心理学书籍', '了解一种心理学理论', '尝试心理测试'],
    },
    {
      id: 39,
      icon: '😴',
      name: '睡眠周',
      description: '改善睡眠质量，让身体充分休息',
      category: 'psychology',
      tags: ['心理', '健康'],
      participants: 289,
      ideas: ['每天11点前入睡', '睡前不玩手机', '记录睡眠时长'],
    },
    {
      id: 40,
      icon: '📔',
      name: '日记周',
      description: '记录内心想法，梳理情绪脉络',
      category: 'psychology',
      tags: ['心理', '记录'],
      participants: 198,
      ideas: ['每天写日记', '记录情绪变化', '进行自我反思'],
    },
    {
      id: 41,
      icon: '🌿',
      name: '正念周',
      description: '活在当下，感受每一刻的美好',
      category: 'psychology',
      tags: ['心理', '冥想'],
      participants: 156,
      ideas: ['练习正念呼吸', '正念饮食', '正念行走'],
    },
    {
      id: 42,
      icon: '💭',
      name: '情绪管理周',
      description: '学会识别和调节情绪，做情绪的主人',
      category: 'psychology',
      tags: ['心理', '成长'],
      participants: 234,
      ideas: ['记录情绪日记', '学习情绪调节技巧', '练习深呼吸'],
    },
    {
      id: 43,
      icon: '🎯',
      name: '专注力周',
      description: '训练注意力，提高工作效率',
      category: 'psychology',
      tags: ['心理', '效率'],
      participants: 178,
      ideas: ['练习番茄工作法', '减少多任务处理', '进行专注力训练'],
    },
    {
      id: 44,
      icon: '🌈',
      name: '积极心理周',
      description: '培养乐观心态，发现生活美好',
      category: 'psychology',
      tags: ['心理', '幸福'],
      participants: 212,
      ideas: ['每天记录三件好事', '练习积极自我对话', '培养感恩习惯'],
    },
    {
      id: 45,
      icon: '💞',
      name: '共情周',
      description: '理解他人感受，建立深度连接',
      category: 'psychology',
      tags: ['心理', '社交'],
      participants: 134,
      ideas: ['练习换位思考', '主动倾听他人', '表达理解与支持'],
    },
    {
      id: 46,
      icon: '💪',
      name: '自信周',
      description: '建立自信，勇敢面对挑战',
      category: 'psychology',
      tags: ['心理', '成长'],
      participants: 267,
      ideas: ['记录自己的优点', '挑战一件害怕的事', '练习自我肯定'],
    },
    {
      id: 47,
      icon: '🌱',
      name: '成长型思维周',
      description: '拥抱挑战，相信能力可以培养',
      category: 'psychology',
      tags: ['心理', '成长'],
      participants: 189,
      ideas: ['学习成长型思维', '将失败视为学习机会', '寻求反馈意见'],
    },
    {
      id: 48,
      icon: '⚖️',
      name: '平衡周',
      description: '寻找工作与生活平衡，减少内耗',
      category: 'psychology',
      tags: ['心理', '生活'],
      participants: 223,
      ideas: ['设定工作边界', '安排休闲时间', '练习说不'],
    },

    // 文化类 (12个)
    {
      id: 49,
      icon: '🏛',
      name: '博物馆周',
      description: '走进博物馆，与历史对话',
      category: 'culture',
      tags: ['文化', '历史'],
      participants: 156,
      ideas: ['参观一座博物馆', '了解一件文物', '学习展览策划'],
    },
    {
      id: 50,
      icon: '📜',
      name: '诗词周',
      description: '品味古典诗词，感受文字之美',
      category: 'culture',
      tags: ['文化', '文学'],
      participants: 198,
      ideas: ['背诵一首古诗', '了解诗人故事', '尝试写一首诗'],
    },
    {
      id: 51,
      icon: '🧧',
      name: '传统节日周',
      description: '了解传统节日，传承文化根脉',
      category: 'culture',
      tags: ['文化', '传统'],
      participants: 234,
      ideas: ['了解一个传统节日', '学习相关习俗', '制作传统美食'],
    },
    {
      id: 52,
      icon: '🎎',
      name: '民俗周',
      description: '探索民间文化，感受乡土情怀',
      category: 'culture',
      tags: ['文化', '民间'],
      participants: 112,
      ideas: ['了解一种民俗', '学习民间工艺', '听老人讲故事'],
    },
    {
      id: 53,
      icon: '🏯',
      name: '古建筑周',
      description: '探访古建筑，感受历史厚重',
      category: 'culture',
      tags: ['文化', '建筑'],
      participants: 145,
      ideas: ['参观一处古建筑', '了解建筑特点', '学习建筑历史'],
    },
    {
      id: 54,
      icon: '⛪',
      name: '宗教文化周',
      description: '了解宗教文化，拓宽精神视野',
      category: 'culture',
      tags: ['文化', '精神'],
      participants: 89,
      ideas: ['了解一种宗教', '参观宗教场所', '学习宗教艺术'],
    },
    {
      id: 55,
      icon: '🎭',
      name: '戏曲周',
      description: '欣赏传统戏曲，感受国粹魅力',
      category: 'culture',
      tags: ['文化', '表演'],
      participants: 134,
      ideas: ['观看一场戏曲', '了解戏曲种类', '学习戏曲知识'],
    },
    {
      id: 56,
      icon: '🍵',
      name: '茶道周',
      description: '品茶悟道，感受东方美学',
      category: 'culture',
      tags: ['文化', '生活'],
      participants: 178,
      ideas: ['学习泡茶技巧', '了解茶叶种类', '体验茶席布置'],
    },
    {
      id: 57,
      icon: '📕',
      name: '名著周',
      description: '重读经典名著，汲取人生智慧',
      category: 'culture',
      tags: ['文化', '文学'],
      participants: 245,
      ideas: ['读一本名著', '了解作者生平', '分析作品主题'],
    },
    {
      id: 58,
      icon: '🗿',
      name: '考古周',
      description: '探索古代文明，解开历史谜团',
      category: 'culture',
      tags: ['文化', '历史'],
      participants: 98,
      ideas: ['了解考古发现', '参观考古遗址', '学习文物保护'],
    },
    {
      id: 59,
      icon: '🖼️',
      name: '国画周',
      description: '学习传统绘画，感受东方意境',
      category: 'culture',
      tags: ['文化', '艺术'],
      participants: 123,
      ideas: ['了解国画种类', '学习基础技法', '完成一幅作品'],
    },
    {
      id: 60,
      icon: '🎵',
      name: '民乐周',
      description: '聆听民族音乐，感受传统韵律',
      category: 'culture',
      tags: ['文化', '音乐'],
      participants: 156,
      ideas: ['了解民族乐器', '听民乐演奏', '学习一种乐器'],
    },

    // 技能类 (12个)
    {
      id: 61,
      icon: '💻',
      name: '编程周',
      description: '学习编程，用代码创造可能',
      category: 'skills',
      tags: ['技能', '科技'],
      participants: 312,
      ideas: ['完成一个编程入门课程', '写一个小程序', '学习一种新语言'],
    },
    {
      id: 62,
      icon: '🎤',
      name: '演讲周',
      description: '提升表达能力，勇敢说出自己的想法',
      category: 'skills',
      tags: ['技能', '沟通'],
      participants: 178,
      ideas: ['每天练习演讲5分钟', '录制一段演讲视频', '参加一次公开演讲'],
    },
    {
      id: 63,
      icon: '✍️',
      name: '写作周',
      description: '提升写作能力，清晰表达思想',
      category: 'skills',
      tags: ['技能', '创作'],
      participants: 245,
      ideas: ['每天写一篇短文', '学习写作技巧', '完成一篇长文'],
    },
    {
      id: 64,
      icon: '📑',
      name: 'PPT周',
      description: '制作精美演示文稿，提升职场竞争力',
      category: 'skills',
      tags: ['技能', '职场'],
      participants: 289,
      ideas: ['学习PPT设计原则', '制作一份演示文稿', '学习动画效果'],
    },
    {
      id: 65,
      icon: '📹',
      name: '视频剪辑周',
      description: '学习剪辑技巧，制作精彩视频',
      category: 'skills',
      tags: ['技能', '创作'],
      participants: 234,
      ideas: ['学习剪辑软件', '剪辑一个短片', '学习转场技巧'],
    },
    {
      id: 66,
      icon: '📷',
      name: '摄影技巧周',
      description: '提升摄影水平，拍出大片感',
      category: 'skills',
      tags: ['技能', '艺术'],
      participants: 198,
      ideas: ['学习光线运用', '练习构图技巧', '后期调色'],
    },
    {
      id: 67,
      icon: '✏️',
      name: '设计周',
      description: '学习设计原理，提升审美能力',
      category: 'skills',
      tags: ['技能', '艺术'],
      participants: 167,
      ideas: ['学习设计软件', '了解设计原则', '完成一个设计作品'],
    },
    {
      id: 68,
      icon: '👨‍🍳',
      name: '烹饪技巧周',
      description: '提升厨艺，做出美味佳肴',
      category: 'skills',
      tags: ['技能', '生活'],
      participants: 312,
      ideas: ['学习刀工', '掌握火候', '尝试新菜式'],
    },
    {
      id: 69,
      icon: '🚙',
      name: '驾驶周',
      description: '提升驾驶技术，安全出行',
      category: 'skills',
      tags: ['技能', '实用'],
      participants: 178,
      ideas: ['练习倒车入库', '学习防御性驾驶', '了解车辆保养'],
    },
    {
      id: 70,
      icon: '💄',
      name: '化妆周',
      description: '学习化妆技巧，提升个人形象',
      category: 'skills',
      tags: ['技能', '形象'],
      participants: 234,
      ideas: ['学习底妆技巧', '练习眼妆', '了解色彩搭配'],
    },
    {
      id: 71,
      icon: '🪡',
      name: '缝纫周',
      description: '学习缝纫技能，改造旧衣物',
      category: 'skills',
      tags: ['技能', '手工'],
      participants: 123,
      ideas: ['学习基础针法', '缝补衣物', '制作简单布艺'],
    },
    {
      id: 72,
      icon: '🔧',
      name: '维修周',
      description: '学习维修技能，解决生活小问题',
      category: 'skills',
      tags: ['技能', '实用'],
      participants: 156,
      ideas: ['学习换灯泡', '修理水龙头', '了解电路知识'],
    },

    // 旅行类 (12个)
    {
      id: 73,
      icon: '🎒',
      name: '城市探索周',
      description: '深度探索所在城市，发现隐藏美景',
      category: 'travel',
      tags: ['旅行', '探索'],
      participants: 267,
      ideas: ['探索一条老街', '发现一家特色店', '了解城市历史'],
    },
    {
      id: 74,
      icon: '🏕️',
      name: '露营周',
      description: '亲近自然，体验户外生活',
      category: 'travel',
      tags: ['旅行', '户外'],
      participants: 198,
      ideas: ['准备露营装备', '选择露营地点', '学习野外生存'],
    },
    {
      id: 75,
      icon: '🏔️',
      name: '登山周',
      description: '攀登高峰，挑战自我',
      category: 'travel',
      tags: ['旅行', '挑战'],
      participants: 156,
      ideas: ['选择一座山', '准备登山装备', '学习登山技巧'],
    },
    {
      id: 76,
      icon: '🏖️',
      name: '海岛周',
      description: '享受阳光沙滩，放松身心',
      category: 'travel',
      tags: ['旅行', '休闲'],
      participants: 234,
      ideas: ['计划海岛行程', '体验水上运动', '欣赏日出日落'],
    },
    {
      id: 77,
      icon: '🚂',
      name: '火车旅行周',
      description: '慢游沿途风景，感受旅途诗意',
      category: 'travel',
      tags: ['旅行', '慢游'],
      participants: 145,
      ideas: ['选择一条铁路线', '欣赏沿途风景', '体验火车文化'],
    },
    {
      id: 78,
      icon: '🚗',
      name: '自驾游周',
      description: '自由驰骋，探索未知路途',
      category: 'travel',
      tags: ['旅行', '自由'],
      participants: 289,
      ideas: ['规划自驾路线', '检查车辆状况', '记录沿途风景'],
    },
    {
      id: 79,
      icon: '🏮',
      name: '古镇周',
      description: '漫步古镇，感受岁月静好',
      category: 'travel',
      tags: ['旅行', '文化'],
      participants: 178,
      ideas: ['游览古镇景点', '品尝当地美食', '了解古镇历史'],
    },
    {
      id: 80,
      icon: '🌸',
      name: '赏花周',
      description: '追随花季，欣赏自然之美',
      category: 'travel',
      tags: ['旅行', '自然'],
      participants: 312,
      ideas: ['了解花期信息', '前往赏花地点', '拍摄花卉照片'],
    },
    {
      id: 81,
      icon: '🍜',
      name: '美食之旅周',
      description: '品尝各地美食，探索饮食文化',
      category: 'travel',
      tags: ['旅行', '美食'],
      participants: 267,
      ideas: ['寻找当地特色', '尝试街头小吃', '学习制作当地菜'],
    },
    {
      id: 82,
      icon: '🗺️',
      name: '摄影旅行周',
      description: '用镜头记录旅途中的美好',
      category: 'travel',
      tags: ['旅行', '摄影'],
      participants: 198,
      ideas: ['规划拍摄主题', '寻找最佳机位', '记录旅行故事'],
    },
    {
      id: 83,
      icon: '⛺',
      name: '背包客周',
      description: '轻装上阵，体验背包旅行',
      category: 'travel',
      tags: ['旅行', '经济'],
      participants: 134,
      ideas: ['精简行李', '选择经济住宿', '与当地人交流'],
    },
    {
      id: 84,
      icon: '🌃',
      name: '夜景周',
      description: '欣赏城市夜景，感受别样魅力',
      category: 'travel',
      tags: ['旅行', '城市'],
      participants: 223,
      ideas: ['寻找观景点', '拍摄夜景', '体验夜生活'],
    },

    // 手工类 (12个)
    {
      id: 85,
      icon: '🧣',
      name: '钩织周',
      description: '用双手创造温暖，编织生活的美好',
      category: 'handicraft',
      tags: ['手工', '生活'],
      participants: 186,
      ideas: ['学会基础钩织针法', '完成一个小作品', '尝试新花样'],
    },
    {
      id: 86,
      icon: '🏺',
      name: '陶艺周',
      description: '感受泥土的温度，塑造独特的作品',
      category: 'handicraft',
      tags: ['手工', '艺术'],
      participants: 98,
      ideas: ['学习拉坯技巧', '制作一个杯子', '尝试釉上彩'],
    },
    {
      id: 87,
      icon: '💐',
      name: '插花周',
      description: '用花艺装点生活，感受自然之美',
      category: 'handicraft',
      tags: ['手工', '生活'],
      participants: 156,
      ideas: ['学习基础插花技巧', '完成一个花艺作品', '了解花材搭配'],
    },
    {
      id: 88,
      icon: '✂️',
      name: '剪纸周',
      description: '一把剪刀一张纸，创造无限可能',
      category: 'handicraft',
      tags: ['手工', '传统'],
      participants: 112,
      ideas: ['学习基础剪法', '完成一幅作品', '了解剪纸文化'],
    },
    {
      id: 89,
      icon: '🕯️',
      name: '蜡烛周',
      description: '制作香薰蜡烛，营造温馨氛围',
      category: 'handicraft',
      tags: ['手工', '生活'],
      participants: 178,
      ideas: ['学习蜡烛制作', '调配香薰精油', '设计蜡烛造型'],
    },
    {
      id: 90,
      icon: '🧵',
      name: '刺绣周',
      description: '一针一线，绣出精美图案',
      category: 'handicraft',
      tags: ['手工', '传统'],
      participants: 134,
      ideas: ['学习基础针法', '完成一幅小绣品', '了解刺绣文化'],
    },
    {
      id: 91,
      icon: '📿',
      name: '串珠周',
      description: '用珠子串出美丽饰品',
      category: 'handicraft',
      tags: ['手工', '饰品'],
      participants: 98,
      ideas: ['学习串珠技巧', '设计一款手链', '了解珠子种类'],
    },
    {
      id: 92,
      icon: '📦',
      name: '折纸周',
      description: '一张白纸，折出万千世界',
      category: 'handicraft',
      tags: ['手工', '创意'],
      participants: 145,
      ideas: ['学习基础折法', '折一只千纸鹤', '尝试复杂造型'],
    },
    {
      id: 93,
      icon: '💎',
      name: '滴胶周',
      description: '用滴胶封存美好，制作独特饰品',
      category: 'handicraft',
      tags: ['手工', '创意'],
      participants: 167,
      ideas: ['学习滴胶制作', '制作一个挂件', '尝试分层效果'],
    },
    {
      id: 94,
      icon: '🧼',
      name: '手工皂周',
      description: '制作天然手工皂，呵护肌肤',
      category: 'handicraft',
      tags: ['手工', '生活'],
      participants: 189,
      ideas: ['了解皂化反应', '制作一块手工皂', '添加天然精油'],
    },
    {
      id: 95,
      icon: '🎁',
      name: '皮具周',
      description: '学习皮具制作，打造专属物品',
      category: 'handicraft',
      tags: ['手工', '技能'],
      participants: 123,
      ideas: ['了解皮革知识', '制作一个卡包', '学习缝线技巧'],
    },
    {
      id: 96,
      icon: '💡',
      name: '灯笼周',
      description: '制作传统灯笼，点亮节日氛围',
      category: 'handicraft',
      tags: ['手工', '传统'],
      participants: 89,
      ideas: ['学习灯笼结构', '制作一个灯笼', '了解灯笼文化'],
    },

    // 社交类 (12个)
    {
      id: 97,
      icon: '👋',
      name: '交友周',
      description: '主动认识新朋友，拓展社交圈',
      category: 'social',
      tags: ['社交', '交友'],
      participants: 156,
      ideas: ['主动认识一个新朋友', '参加一次社交活动', '约朋友喝咖啡'],
    },
    {
      id: 98,
      icon: '❤️',
      name: '志愿者周',
      description: '用爱心回馈社会，感受奉献的快乐',
      category: 'social',
      tags: ['社交', '公益'],
      participants: 134,
      ideas: ['参加一次志愿活动', '帮助一个需要帮助的人', '了解公益组织'],
    },
    {
      id: 99,
      icon: '🎉',
      name: '聚会周',
      description: '组织一场聚会，与朋友共度美好时光',
      category: 'social',
      tags: ['社交', '聚会'],
      participants: 178,
      ideas: ['组织一次朋友聚会', '尝试新的聚会形式', '准备一个惊喜'],
    },
    {
      id: 100,
      icon: '💬',
      name: '沟通周',
      description: '提升沟通技巧，建立更好的人际关系',
      category: 'social',
      tags: ['社交', '沟通'],
      participants: 198,
      ideas: ['练习倾听技巧', '学习表达感受', '进行一次深度对话'],
    },
    {
      id: 101,
      icon: '🙏',
      name: '感恩周',
      description: '学会感恩，发现生活中的美好',
      category: 'social',
      tags: ['社交', '心理'],
      participants: 234,
      ideas: ['每天写感恩日记', '向一个人表达感谢', '发现生活中的小确幸'],
    },
    {
      id: 102,
      icon: '🤝',
      name: '分享周',
      description: '分享知识与经验，帮助他人成长',
      category: 'social',
      tags: ['社交', '分享'],
      participants: 167,
      ideas: ['分享一个技能', '写一篇经验分享', '帮助一个朋友'],
    },
    {
      id: 103,
      icon: '👂',
      name: '倾听周',
      description: '学会倾听，理解他人的感受',
      category: 'social',
      tags: ['社交', '沟通'],
      participants: 145,
      ideas: ['专注倾听一个人', '不打断别人说话', '练习共情能力'],
    },
    {
      id: 104,
      icon: '👨‍👩‍👧‍',
      name: '陪伴周',
      description: '花时间陪伴家人，珍惜在一起的时光',
      category: 'social',
      tags: ['社交', '家庭'],
      participants: 212,
      ideas: ['陪家人吃一顿饭', '陪父母散步', '和家人一起看电影'],
    },
    {
      id: 105,
      icon: '🏘️',
      name: '社区周',
      description: '参与社区活动，认识身边的邻居',
      category: 'social',
      tags: ['社交', '社区'],
      participants: 98,
      ideas: ['参加一次社区活动', '认识一位邻居', '了解社区资源'],
    },
    {
      id: 106,
      icon: '🌟',
      name: '公益周',
      description: '关注社会问题，用行动传递温暖',
      category: 'social',
      tags: ['社交', '公益'],
      participants: 156,
      ideas: ['了解一个社会问题', '参与一次公益活动', '捐赠闲置物品'],
    },
    {
      id: 107,
      icon: '🤗',
      name: '拥抱周',
      description: '用拥抱传递温暖，增进亲密关系',
      category: 'social',
      tags: ['社交', '情感'],
      participants: 134,
      ideas: ['每天拥抱家人', '给朋友一个拥抱', '了解拥抱的好处'],
    },
    {
      id: 108,
      icon: '🔄',
      name: '角色互换周',
      description: '体验不同角色，增进相互理解',
      category: 'social',
      tags: ['社交', '体验'],
      participants: 89,
      ideas: ['体验朋友的工作', '互换家庭角色', '了解不同职业'],
    },

    // 生活类 (12个)
    {
      id: 109,
      icon: '🍳',
      name: '烹饪周',
      description: '探索美食的奥秘，享受烹饪的乐趣',
      category: 'life',
      tags: ['生活', '美食'],
      participants: 289,
      ideas: ['学做一道新菜', '尝试不同国家料理', '记录食谱'],
    },
    {
      id: 110,
      icon: '☕',
      name: '咖啡周',
      description: '品味不同产地的咖啡，感受咖啡文化',
      category: 'life',
      tags: ['生活', '美食'],
      participants: 256,
      ideas: ['品尝不同产地咖啡', '学习手冲咖啡', '了解咖啡知识'],
    },
    {
      id: 111,
      icon: '🧹',
      name: '整理周',
      description: '整理空间，也整理心情',
      category: 'life',
      tags: ['生活', '整理'],
      participants: 312,
      ideas: ['整理一个房间', '断舍离不需要的物品', '建立收纳系统'],
    },
    {
      id: 112,
      icon: '👗',
      name: '穿搭周',
      description: '探索个人风格，穿出自信',
      category: 'life',
      tags: ['生活', '时尚'],
      participants: 234,
      ideas: ['尝试不同风格', '整理衣柜', '学习色彩搭配'],
    },
    {
      id: 113,
      icon: '🏠',
      name: '极简周',
      description: '简化生活，回归本质',
      category: 'life',
      tags: ['生活', '极简'],
      participants: 267,
      ideas: ['减少不必要的消费', '简化日常流程', '专注重要事物'],
    },
    {
      id: 114,
      icon: '🎧',
      name: '歌单周',
      description: '整理心情歌单，用音乐陪伴每一天',
      category: 'life',
      tags: ['生活', '音乐'],
      participants: 223,
      ideas: ['创建主题歌单', '发现新音乐', '分享喜欢的歌曲'],
    },
    {
      id: 115,
      icon: '🪴',
      name: '园艺周',
      description: '与植物为伴，感受生命的力量',
      category: 'life',
      tags: ['生活', '自然'],
      participants: 178,
      ideas: ['种植一盆植物', '学习浇水技巧', '了解植物习性'],
    },
    {
      id: 116,
      icon: '📝',
      name: '记录周',
      description: '用照片和文字记录生活点滴',
      category: 'life',
      tags: ['生活', '记录'],
      participants: 198,
      ideas: ['每天拍一张照片', '写一篇生活日记', '制作生活相册'],
    },
    {
      id: 117,
      icon: '🌙',
      name: '早睡早起周',
      description: '调整作息，养成健康生活习惯',
      category: 'life',
      tags: ['生活', '健康'],
      participants: 289,
      ideas: ['每天11点前睡', '早上7点起', '记录精力变化'],
    },
    {
      id: 118,
      icon: '📱',
      name: '数字排毒周',
      description: '减少屏幕时间，回归真实生活',
      category: 'life',
      tags: ['生活', '健康'],
      participants: 234,
      ideas: ['每天少刷1小时手机', '用纸质书代替电子书', '多面对面交流'],
    },
    {
      id: 119,
      icon: '🍱',
      name: '便当周',
      description: '制作精美便当，享受带饭乐趣',
      category: 'life',
      tags: ['生活', '美食'],
      participants: 156,
      ideas: ['学习便当搭配', '准备一周便当', '注重营养均衡'],
    },
    {
      id: 120,
      icon: '🌅',
      name: '晨间仪式周',
      description: '建立晨间习惯，开启美好一天',
      category: 'life',
      tags: ['生活', '习惯'],
      participants: 178,
      ideas: ['早起喝一杯水', '做晨间拉伸', '规划一天任务'],
    },

    // 健康类 (12个)
    {
      id: 121,
      icon: '🥗',
      name: '健康饮食周',
      description: '关注饮食健康，吃出好身体',
      category: 'health',
      tags: ['健康', '饮食'],
      participants: 312,
      ideas: ['每天吃五种蔬菜', '减少糖分摄入', '学习营养搭配'],
    },
    {
      id: 122,
      icon: '🛌',
      name: '睡眠改善周',
      description: '改善睡眠质量，让身体充分休息',
      category: 'health',
      tags: ['健康', '作息'],
      participants: 289,
      ideas: ['每天11点前入睡', '睡前不玩手机', '记录睡眠时长'],
    },
    {
      id: 123,
      icon: '💧',
      name: '喝水周',
      description: '养成喝水习惯，保持身体水分',
      category: 'health',
      tags: ['健康', '习惯'],
      participants: 198,
      ideas: ['每天喝8杯水', '设置喝水提醒', '记录喝水量'],
    },
    {
      id: 124,
      icon: '🦷',
      name: '口腔护理周',
      description: '关注口腔健康，养成护理习惯',
      category: 'health',
      tags: ['健康', '护理'],
      participants: 156,
      ideas: ['正确刷牙方法', '使用牙线', '定期口腔检查'],
    },
    {
      id: 125,
      icon: '👁️',
      name: '护眼周',
      description: '保护视力，缓解眼部疲劳',
      category: 'health',
      tags: ['健康', '护理'],
      participants: 267,
      ideas: ['做眼保健操', '每20分钟看远处', '减少屏幕时间'],
    },
    {
      id: 126,
      icon: '🧴',
      name: '护肤周',
      description: '建立护肤 routine，呵护肌肤',
      category: 'health',
      tags: ['健康', '护理'],
      participants: 234,
      ideas: ['了解肤质', '建立护肤步骤', '注意防晒'],
    },
    {
      id: 127,
      icon: '🚶',
      name: '日行万步周',
      description: '增加日常活动量，保持身体活力',
      category: 'health',
      tags: ['健康', '运动'],
      participants: 312,
      ideas: ['每天走10000步', '选择步行代替乘车', '记录步数'],
    },
    {
      id: 128,
      icon: '🦵',
      name: '拉伸周',
      description: '每天拉伸，保持身体柔韧',
      category: 'health',
      tags: ['健康', '运动'],
      participants: 178,
      ideas: ['早上拉伸10分钟', '工作间隙拉伸', '睡前放松拉伸'],
    },
    {
      id: 129,
      icon: '🌞',
      name: '晒太阳周',
      description: '适度晒太阳，补充维生素D',
      category: 'health',
      tags: ['健康', '自然'],
      participants: 134,
      ideas: ['每天户外15分钟', '选择合适时间', '注意防晒'],
    },
    {
      id: 130,
      icon: '🫁',
      name: '呼吸训练周',
      description: '练习深呼吸，缓解压力焦虑',
      category: 'health',
      tags: ['健康', '心理'],
      participants: 156,
      ideas: ['练习腹式呼吸', '尝试4-7-8呼吸法', '冥想时关注呼吸'],
    },
    {
      id: 131,
      icon: '🦶',
      name: '足部护理周',
      description: '关爱双脚，缓解疲劳',
      category: 'health',
      tags: ['健康', '护理'],
      participants: 123,
      ideas: ['每天泡脚', '按摩足底', '选择舒适鞋袜'],
    },
    {
      id: 132,
      icon: '🧠',
      name: '脑力训练周',
      description: '锻炼大脑，保持思维敏捷',
      category: 'health',
      tags: ['健康', '认知'],
      participants: 198,
      ideas: ['做数独', '学习新技能', '玩记忆游戏'],
    },

    // 语言类 (12个)
    {
      id: 133,
      icon: '🇬🇧',
      name: '英语周',
      description: '提升英语能力，打开国际视野',
      category: 'language',
      tags: ['语言', '英语'],
      participants: 456,
      ideas: ['每天背单词', '看一部英文电影', '练习口语'],
    },
    {
      id: 134,
      icon: '🇯🇵',
      name: '日语周',
      description: '学习日语，了解日本文化',
      category: 'language',
      tags: ['语言', '日语'],
      participants: 234,
      ideas: ['学习五十音图', '看一部动漫', '学一首日语歌'],
    },
    {
      id: 135,
      icon: '🇰🇷',
      name: '韩语周',
      description: '学习韩语，追韩剧不用字幕',
      category: 'language',
      tags: ['语言', '韩语'],
      participants: 198,
      ideas: ['学习韩文字母', '看一部韩剧', '学一首K-pop歌曲'],
    },
    {
      id: 136,
      icon: '🇫🇷',
      name: '法语周',
      description: '学习浪漫法语，感受法式优雅',
      category: 'language',
      tags: ['语言', '法语'],
      participants: 156,
      ideas: ['学习基础发音', '了解法国文化', '学一首法语歌'],
    },
    {
      id: 137,
      icon: '🇩🇪',
      name: '德语周',
      description: '学习严谨德语，了解德国文化',
      category: 'language',
      tags: ['语言', '德语'],
      participants: 123,
      ideas: ['学习基础语法', '了解德国历史', '学一首德语歌'],
    },
    {
      id: 138,
      icon: '🇪🇸',
      name: '西语周',
      description: '学习热情西语，探索拉美文化',
      category: 'language',
      tags: ['语言', '西语'],
      participants: 178,
      ideas: ['学习基础发音', '看一部西语电影', '了解西班牙文化'],
    },
    {
      id: 139,
      icon: '🇮🇹',
      name: '意大利语周',
      description: '学习优美意语，感受艺术之国',
      category: 'language',
      tags: ['语言', '意语'],
      participants: 112,
      ideas: ['学习基础对话', '了解意大利艺术', '学一首意大利歌'],
    },
    {
      id: 140,
      icon: '🇷🇺',
      name: '俄语周',
      description: '学习俄语，了解战斗民族',
      category: 'language',
      tags: ['语言', '俄语'],
      participants: 89,
      ideas: ['学习西里尔字母', '了解俄国文学', '学一首俄语歌'],
    },
    {
      id: 141,
      icon: '🇵🇹',
      name: '葡萄牙语周',
      description: '学习葡语，探索巴西风情',
      category: 'language',
      tags: ['语言', '葡语'],
      participants: 67,
      ideas: ['学习基础发音', '了解巴西文化', '学一首葡语歌'],
    },
    {
      id: 142,
      icon: '🇦🇪',
      name: '阿拉伯语周',
      description: '学习阿拉伯语，了解中东文化',
      category: 'language',
      tags: ['语言', '阿语'],
      participants: 45,
      ideas: ['学习阿拉伯字母', '了解伊斯兰文化', '学一句问候语'],
    },
    {
      id: 143,
      icon: '🇹🇭',
      name: '泰语周',
      description: '学习泰语，感受微笑国度',
      category: 'language',
      tags: ['语言', '泰语'],
      participants: 78,
      ideas: ['学习泰语声调', '了解泰国文化', '学一句萨瓦迪卡'],
    },
    {
      id: 144,
      icon: '🇻🇳',
      name: '越南语周',
      description: '学习越南语，了解东南亚风情',
      category: 'language',
      tags: ['语言', '越南语'],
      participants: 56,
      ideas: ['学习越南语发音', '了解越南历史', '学一首越南歌'],
    },
  ]);

  // 我的主题周
  const myWeeks = ref([
    {
      id: 1,
      icon: '🎼',
      name: '音乐剧周',
      startDate: '2026-04-20',
      endDate: '2026-04-26',
      description: '走进剧场，感受音乐与戏剧的碰撞',
      status: 'ongoing',
      statusText: '进行中',
      progress: 60,
      tasks: ['看一场音乐剧', '学一首音乐剧歌曲', '了解音乐剧历史'],
      dayCheckins: [true, true, true, true, false, false, false],
      checkins: [
        { date: '2026-04-20', content: '今天去看了《歌剧魅影》', mood: 5 },
        { date: '2026-04-21', content: '听了《悲惨世界》原声带', mood: 4 },
        { date: '2026-04-22', content: '了解音乐剧历史', mood: 4 },
        { date: '2026-04-23', content: '学唱《Do You Hear the People Sing》', mood: 5 },
      ],
    },
    {
      id: 2,
      icon: '📗',
      name: '阅读周',
      startDate: '2026-04-13',
      endDate: '2026-04-19',
      description: '放下手机，沉浸在文字的世界里',
      status: 'completed',
      statusText: '已完成',
      progress: 100,
      dayCheckins: [true, true, true, true, true, true, true],
      checkins: [
        { date: '2026-04-13', content: '开始读《百年孤独》', mood: 5 },
        { date: '2026-04-14', content: '读完了第一章', mood: 4 },
        { date: '2026-04-15', content: '写了第一篇读书笔记', mood: 5 },
      ],
      achievements: ['读完《百年孤独》', '写读书笔记3篇'],
    },
    {
      id: 3,
      icon: '🧶',
      name: '钩织周',
      startDate: '2026-04-06',
      endDate: '2026-04-12',
      description: '用双手创造温暖，编织生活的美好',
      status: 'completed',
      statusText: '已完成',
      progress: 100,
      dayCheckins: [true, true, true, true, true, true, true],
      checkins: [
        { date: '2026-04-06', content: '学会了基础针法', mood: 5 },
        { date: '2026-04-08', content: '完成了第一个杯垫', mood: 5 },
      ],
      achievements: ['学会基础针法', '完成杯垫2个'],
    },
  ]);

  // 感悟墙
  const insights = ref([
    {
      id: 1,
      avatar: '👧',
      user: '小叶子',
      theme: '🎭 音乐剧周',
      date: '2026-04-20',
      content: '第一次走进剧场看音乐剧，被《歌剧魅影》深深震撼了！',
      tags: ['#音乐剧', '#新体验'],
      likes: 24,
      comments: 6,
    },
    {
      id: 2,
      avatar: '👦',
      user: '阿明',
      theme: '📖 阅读周',
      date: '2026-04-15',
      content: '这周读完了《百年孤独》，马尔克斯的想象力太丰富了',
      tags: ['#阅读', '#马尔克斯'],
      likes: 18,
      comments: 4,
    },
    {
      id: 3,
      avatar: '👩',
      user: '小雨',
      theme: '🧶 钩织周',
      date: '2026-04-08',
      content: '完成了第一个杯垫，虽然歪歪扭扭的但很有成就感！',
      tags: ['#手工', '#钩织'],
      likes: 32,
      comments: 8,
    },
  ]);

  // 获取所有主题
  const getAllThemes = computed(() => themes.value);

  // 根据分类获取主题
  const getThemesByCategory = (categoryId) => {
    if (categoryId === 'all') return themes.value;
    return themes.value.filter(theme => theme.category === categoryId);
  };

  // 添加我的主题周
  const addMyWeek = (week) => {
    const start = new Date(week.startDate);
    const end = new Date(start);
    end.setDate(end.getDate() + 6);
    const endDateStr = end.toISOString().split('T')[0];

    const newWeek = {
      id: Date.now(),
      ...week,
      endDate: endDateStr,
      status: 'ongoing',
      statusText: '进行中',
      progress: 0,
      checkins: [],
      dayCheckins: Array(7).fill(false),
      taskCompleted: [],
    };
    myWeeks.value.unshift(newWeek);
    return newWeek;
  };

  // 获取当前进行中的主题周
  const getCurrentWeek = computed(() => {
    return myWeeks.value.find(w => w.status === 'ongoing') || null;
  });

  // 获取指定主题周
  const getWeekById = (id) => {
    return myWeeks.value.find(w => w.id === id) || null;
  };

  // 切换某天打卡状态
  const toggleDayCheckin = (weekId, dayIndex, content = '') => {
    const week = myWeeks.value.find(w => w.id === weekId);
    if (!week) return;

    const wasChecked = week.dayCheckins[dayIndex];
    week.dayCheckins[dayIndex] = !wasChecked;

    const start = new Date(week.startDate);
    const checkDate = new Date(start);
    checkDate.setDate(checkDate.getDate() + dayIndex);
    const dateStr = checkDate.toISOString().split('T')[0];

    if (!wasChecked) {
      // 添加打卡记录
      week.checkins.unshift({
        date: dateStr,
        content: content || `完成第${dayIndex + 1}天打卡`,
        mood: 5,
      });
    } else {
      // 取消打卡，移除对应记录
      week.checkins = week.checkins.filter(c => c.date !== dateStr);
    }

    // 更新进度
    const checkedCount = week.dayCheckins.filter(Boolean).length;
    week.progress = Math.round((checkedCount / 7) * 100);

    // 如果7天都完成，标记为已完成
    if (checkedCount === 7) {
      week.status = 'completed';
      week.statusText = '已完成';
    }
  };

  // 提交打卡内容
  const submitCheckinContent = (weekId, dayIndex, content) => {
    const week = myWeeks.value.find(w => w.id === weekId);
    if (!week) return;

    const start = new Date(week.startDate);
    const checkDate = new Date(start);
    checkDate.setDate(checkDate.getDate() + dayIndex);
    const dateStr = checkDate.toISOString().split('T')[0];

    const existing = week.checkins.find(c => c.date === dateStr);
    if (existing) {
      existing.content = content;
    } else {
      week.checkins.unshift({
        date: dateStr,
        content,
        mood: 5,
      });
      week.dayCheckins[dayIndex] = true;

      const checkedCount = week.dayCheckins.filter(Boolean).length;
      week.progress = Math.round((checkedCount / 7) * 100);
      if (checkedCount === 7) {
        week.status = 'completed';
        week.statusText = '已完成';
      }
    }
  };

  // 切换任务完成状态
  const toggleTask = (weekId, taskIndex) => {
    const week = myWeeks.value.find(w => w.id === weekId);
    if (!week) return;
    if (!week.taskCompleted) {
      week.taskCompleted = [];
    }
    week.taskCompleted[taskIndex] = !week.taskCompleted[taskIndex];
  };

  // 添加感悟
  const addInsight = (insight) => {
    insights.value.unshift({
      id: Date.now(),
      ...insight,
      date: new Date().toISOString().split('T')[0],
      likes: 0,
      comments: 0,
    });
  };

  return {
    categories,
    themes,
    myWeeks,
    insights,
    getAllThemes,
    getThemesByCategory,
    addMyWeek,
    addInsight,
    getCurrentWeek,
    getWeekById,
    toggleDayCheckin,
    submitCheckinContent,
    toggleTask,
  };
});
